//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveWPF.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveWPF.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progression.
        /// </summary>
        public static string _Empty_1_ {
            get {
                return ResourceManager.GetString("_Empty[1]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ➕ Ajouter Sauvegarde.
        /// </summary>
        public static string add_backup_button {
            get {
                return ResourceManager.GetString("add_backup_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter / Retirer des extensions à encrypter.
        /// </summary>
        public static string add_or_remove_encryption {
            get {
                return ResourceManager.GetString("add_or_remove_encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ex: .txt.
        /// </summary>
        public static string add_or_remove_encryption_holder {
            get {
                return ResourceManager.GetString("add_or_remove_encryption_holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter / Retirer des extensions prioritaires.
        /// </summary>
        public static string add_or_remove_priority {
            get {
                return ResourceManager.GetString("add_or_remove_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à et.
        /// </summary>
        public static string and_menu {
            get {
                return ResourceManager.GetString("and_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifications enregistrées. Pour les appliquer, veuillez redémarrer..
        /// </summary>
        public static string app_shutdown {
            get {
                return ResourceManager.GetString("app_shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la sauvegarde : {0}.
        /// </summary>
        public static string backup_error {
            get {
                return ResourceManager.GetString("backup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde {0} a été effectuée avec succès !.
        /// </summary>
        public static string backup_success {
            get {
                return ResourceManager.GetString("backup_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🗃 Sauvegardes.
        /// </summary>
        public static string backups_button {
            get {
                return ResourceManager.GetString("backups_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les sauvegardes {0} ont été effectuées avec succès !.
        /// </summary>
        public static string backups_success {
            get {
                return ResourceManager.GetString("backups_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel Métier.
        /// </summary>
        public static string business_software {
            get {
                return ResourceManager.GetString("business_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ex: notepad.exe.
        /// </summary>
        public static string business_software_holder {
            get {
                return ResourceManager.GetString("business_software_holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel Métier en cours d&apos;exécution..
        /// </summary>
        public static string business_software_running {
            get {
                return ResourceManager.GetString("business_software_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez pas créer plus de 5 travaux..
        /// </summary>
        public static string cant_create_more_job {
            get {
                return ResourceManager.GetString("cant_create_more_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Par mesure de sécurité : impossible de supprimer tant que des travaux sont en cours ! Veuillez arrêter les travaux avant suppression !.
        /// </summary>
        public static string cant_delete {
            get {
                return ResourceManager.GetString("cant_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les changements auront lieu au prochain démarrage.
        /// </summary>
        public static string change_at_restart {
            get {
                return ResourceManager.GetString("change_at_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie du fichier : {0}.
        /// </summary>
        public static string copy_file {
            get {
                return ResourceManager.GetString("copy_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde est terminée ! .
        /// </summary>
        public static string copy_success {
            get {
                return ResourceManager.GetString("copy_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le travail {0} a été créé à l&apos;emplacement {1} depuis {2} à {3} avec un type {4}.
        /// </summary>
        public static string create_job_success {
            get {
                return ResourceManager.GetString("create_job_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création.
        /// </summary>
        public static string creation {
            get {
                return ResourceManager.GetString("creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sombre.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le travail numéro {0} a été supprimé avec succès..
        /// </summary>
        public static string delete_job_success {
            get {
                return ResourceManager.GetString("delete_job_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un nouveau travail de sauvegarde.
        /// </summary>
        public static string desc_create {
            get {
                return ResourceManager.GetString("desc_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un travail de sauvegarde.
        /// </summary>
        public static string desc_delete {
            get {
                return ResourceManager.GetString("desc_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Régler les options (comme la langue).
        /// </summary>
        public static string desc_options {
            get {
                return ResourceManager.GetString("desc_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer un travail de sauvegarde.
        /// </summary>
        public static string desc_run {
            get {
                return ResourceManager.GetString("desc_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher un travail de sauvegarde.
        /// </summary>
        public static string desc_show {
            get {
                return ResourceManager.GetString("desc_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        public static string header_id {
            get {
                return ResourceManager.GetString("header_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string header_name {
            get {
                return ResourceManager.GetString("header_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progression (%).
        /// </summary>
        public static string header_progress {
            get {
                return ResourceManager.GetString("header_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string header_source {
            get {
                return ResourceManager.GetString("header_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string header_status {
            get {
                return ResourceManager.GetString("header_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string header_target {
            get {
                return ResourceManager.GetString("header_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string header_type {
            get {
                return ResourceManager.GetString("header_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ID doit être un nombre..
        /// </summary>
        public static string id_must_number {
            get {
                return ResourceManager.GetString("id_must_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du fichier {0} n&apos;est pas autorisé pour la sauvegarde..
        /// </summary>
        public static string incorrect_format {
            get {
                return ResourceManager.GetString("incorrect_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension invalide. L&apos;extension doit commencer par un point (.) et ne pas contenir d&apos;espace.
        /// </summary>
        public static string invalid_extension {
            get {
                return ResourceManager.GetString("invalid_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le travail {0} n&apos;existe pas.
        /// </summary>
        public static string job_doesnt_exist {
            get {
                return ResourceManager.GetString("job_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécution du travail de sauvegarde : {0}.
        /// </summary>
        public static string job_execution {
            get {
                return ResourceManager.GetString("job_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du Travail.
        /// </summary>
        public static string job_name {
            get {
                return ResourceManager.GetString("job_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clair.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des extensions à encrypter.
        /// </summary>
        public static string list_extension_encryption {
            get {
                return ResourceManager.GetString("list_extension_encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des extensions prioritaires.
        /// </summary>
        public static string list_extension_priority {
            get {
                return ResourceManager.GetString("list_extension_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format des logs.
        /// </summary>
        public static string logs_format {
            get {
                return ResourceManager.GetString("logs_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier {0} dépasse la taille maximale autorisée..
        /// </summary>
        public static string maxsize_error {
            get {
                return ResourceManager.GetString("maxsize_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une autre instance de l&apos;application est en cours..
        /// </summary>
        public static string mono_instance_app {
            get {
                return ResourceManager.GetString("mono_instance_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez renseigner un nom.
        /// </summary>
        public static string name_empty {
            get {
                return ResourceManager.GetString("name_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune modification nécessitant l&apos;arrêt de l&apos;application n&apos;a été détectée.
        /// </summary>
        public static string no_changes_made {
            get {
                return ResourceManager.GetString("no_changes_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun travail trouvé.
        /// </summary>
        public static string no_job_found {
            get {
                return ResourceManager.GetString("no_job_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination du répertoire du travail de sauvegarde.
        /// </summary>
        public static string option_dest {
            get {
                return ResourceManager.GetString("option_dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ex: C:\Users\User\Destination.
        /// </summary>
        public static string option_dest_holder {
            get {
                return ResourceManager.GetString("option_dest_holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro du travail de sauvegarde.
        /// </summary>
        public static string option_id {
            get {
                return ResourceManager.GetString("option_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix de la langue.
        /// </summary>
        public static string option_lang {
            get {
                return ResourceManager.GetString("option_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du travail de sauvegarde.
        /// </summary>
        public static string option_name {
            get {
                return ResourceManager.GetString("option_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ex: Sauvegarde1.
        /// </summary>
        public static string option_name_holder {
            get {
                return ResourceManager.GetString("option_name_holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source du répertoire du travail de sauvegarde.
        /// </summary>
        public static string option_source {
            get {
                return ResourceManager.GetString("option_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ex: C:\Users\User\Source.
        /// </summary>
        public static string option_source_holder {
            get {
                return ResourceManager.GetString("option_source_holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix d&apos;un travail de sauvegarde complet.
        /// </summary>
        public static string option_type {
            get {
                return ResourceManager.GetString("option_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les chemins doivent être entre guillemets.
        /// </summary>
        public static string path_must_contain_brackets {
            get {
                return ResourceManager.GetString("path_must_contain_brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez sur une touche pour démarrer....
        /// </summary>
        public static string press_key {
            get {
                return ResourceManager.GetString("press_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La plage de travail de sauvegarde n&apos;est pas valide.
        /// </summary>
        public static string range_not_valid {
            get {
                return ResourceManager.GetString("range_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tout exécuter.
        /// </summary>
        public static string run_all {
            get {
                return ResourceManager.GetString("run_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde en cours d&apos;exécution.
        /// </summary>
        public static string running_backup {
            get {
                return ResourceManager.GetString("running_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentielle.
        /// </summary>
        public static string save_differencial {
            get {
                return ResourceManager.GetString("save_differencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complète.
        /// </summary>
        public static string save_full {
            get {
                return ResourceManager.GetString("save_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type de sauvegarde n&apos;est pas valide..
        /// </summary>
        public static string save_type_error {
            get {
                return ResourceManager.GetString("save_type_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚙️ Paramètres.
        /// </summary>
        public static string settings_button {
            get {
                return ResourceManager.GetString("settings_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille des fichiers(Ko).
        /// </summary>
        public static string size_file_ko {
            get {
                return ResourceManager.GetString("size_file_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire source {0} n&apos;existe pas..
        /// </summary>
        public static string source_directory_doesnt_exist {
            get {
                return ResourceManager.GetString("source_directory_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous sûr de vouloir procéder à la fermeture ? Cette action entraînera l&apos;arrêt de tous les travaux en cours..
        /// </summary>
        public static string stop_before_closing {
            get {
                return ResourceManager.GetString("stop_before_closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Succès.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez renseigner un répertoire de destination.
        /// </summary>
        public static string target_empty {
            get {
                return ResourceManager.GetString("target_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire source et cible ne peuvent pas être les mêmes..
        /// </summary>
        public static string target_source_must_be_different {
            get {
                return ResourceManager.GetString("target_source_must_be_different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thème.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application de sauvegarde de fichiers.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à à .
        /// </summary>
        public static string to_menu {
            get {
                return ResourceManager.GetString("to_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue dans le logiciel de gestion de Sauvegarde EasySave. Écrire &apos;exit&apos; pour quitter..
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
