//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la sauvegarde : {0}.
        /// </summary>
        public static string backup_error {
            get {
                return ResourceManager.GetString("backup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde a été effectuée avec succès !.
        /// </summary>
        public static string backup_success {
            get {
                return ResourceManager.GetString("backup_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez pas créer plus de 5 travaux..
        /// </summary>
        public static string cant_create_more_job {
            get {
                return ResourceManager.GetString("cant_create_more_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les changements auront lieu au prochain démarrage.
        /// </summary>
        public static string change_at_restart {
            get {
                return ResourceManager.GetString("change_at_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie du fichier : {0}.
        /// </summary>
        public static string copy_file {
            get {
                return ResourceManager.GetString("copy_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La copie terminée ! Nombre total de fichiers copiés : {0}.
        /// </summary>
        public static string copy_success {
            get {
                return ResourceManager.GetString("copy_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Le travail {0} a été créé à l&apos;emplacement {1} depuis {2} à {3} avec un type {4}
        ///.
        /// </summary>
        public static string create_job_success {
            get {
                return ResourceManager.GetString("create_job_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le travail numéro {0} a été supprimé avec succès..
        /// </summary>
        public static string delete_job_success {
            get {
                return ResourceManager.GetString("delete_job_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un nouveau travail de sauvegarde.
        /// </summary>
        public static string desc_create {
            get {
                return ResourceManager.GetString("desc_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un travail de sauvegarde.
        /// </summary>
        public static string desc_delete {
            get {
                return ResourceManager.GetString("desc_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Régler les options (comme la langue).
        /// </summary>
        public static string desc_options {
            get {
                return ResourceManager.GetString("desc_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer un travail de sauvegarde.
        /// </summary>
        public static string desc_run {
            get {
                return ResourceManager.GetString("desc_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher un travail de sauvegarde.
        /// </summary>
        public static string desc_show {
            get {
                return ResourceManager.GetString("desc_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ID doit être un nombre..
        /// </summary>
        public static string id_must_number {
            get {
                return ResourceManager.GetString("id_must_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format du fichier {0} n&apos;est pas autorisé pour la sauvegarde..
        /// </summary>
        public static string incorrect_format {
            get {
                return ResourceManager.GetString("incorrect_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le travail {0} n&apos;existe pas.
        /// </summary>
        public static string job_doesnt_exist {
            get {
                return ResourceManager.GetString("job_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécution du travail de sauvegarde : {0}.
        /// </summary>
        public static string job_execution {
            get {
                return ResourceManager.GetString("job_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du Travail.
        /// </summary>
        public static string job_name {
            get {
                return ResourceManager.GetString("job_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier {0} dépasse la taille maximale autorisée..
        /// </summary>
        public static string maxsize_error {
            get {
                return ResourceManager.GetString("maxsize_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun travail trouvé.
        /// </summary>
        public static string no_job_found {
            get {
                return ResourceManager.GetString("no_job_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination du répertoire du travail de sauvegarde (entre guillemets).
        /// </summary>
        public static string option_dest {
            get {
                return ResourceManager.GetString("option_dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro du travail de sauvegarde.
        /// </summary>
        public static string option_id {
            get {
                return ResourceManager.GetString("option_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix de la langue.
        /// </summary>
        public static string option_lang {
            get {
                return ResourceManager.GetString("option_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du travail de sauvegarde.
        /// </summary>
        public static string option_name {
            get {
                return ResourceManager.GetString("option_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source du répertoire du travail de sauvegarde (entre guillemets).
        /// </summary>
        public static string option_source {
            get {
                return ResourceManager.GetString("option_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix d&apos;un travail de sauvegarde complet.
        /// </summary>
        public static string option_type {
            get {
                return ResourceManager.GetString("option_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les chemins doivent être entre guillemets.
        /// </summary>
        public static string path_must_contain_brackets {
            get {
                return ResourceManager.GetString("path_must_contain_brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez sur une touche pour démarrer....
        /// </summary>
        public static string press_key {
            get {
                return ResourceManager.GetString("press_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type de sauvegarde n&apos;est pas valide..
        /// </summary>
        public static string save_type_error {
            get {
                return ResourceManager.GetString("save_type_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire source n&apos;existe pas..
        /// </summary>
        public static string source_directory_doesnt_exist {
            get {
                return ResourceManager.GetString("source_directory_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire source et cible ne peuvent pas être les mêmes..
        /// </summary>
        public static string target_source_must_be_different {
            get {
                return ResourceManager.GetString("target_source_must_be_different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application de sauvegarde de fichiers.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue dans le logiciel de gestion de Sauvegarde EasySave. Écrire &apos;exit&apos; pour quitter..
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
